name: manual trigger
on:
  workflow_dispatch:
    inputs:
      x: 
        description: 'string'
        required: true
        options:
         - one
         - two
         - three
jobs:
    Trigger-manually-workflow:
      name: step1
      runs-on: ubuntu-latest
      steps:
        - name: SayHi
          run: echo ${{github.event.inputs.x}}
  
