name: CI
on: 
  push:
    branches:
      - main
      - main
    paths:
      - "/**"
env:
  app: ${GITHUB_BASE_REF}
jobs:
  Build_And_Test:
    runs-on: [ubuntu-latest]
    steps:
      - name: env
        run: |
          echo ${{ env.app }}
      - name: checkout
        uses: actions/checkout@v3
      - name: set up jdk
        uses: actions/setup-java@v2
        with: 
          java-version: '17'
          distribution: 'adopt'
      - name: maven build artifacts
        run: |
          mvn clean install -f ././demoGitHub/pom.xml -s .// 
        shell: bash
      - name: Temp checking files
        run: |
          cd demoGitHub/target
          ls
      - name: code quality
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_SAML_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.branch.name=main -Dsonar.projectKey=SaiLuckyAss_learnGitHubActions -f ./demoGitHub/pom.xml
        if: false
      - name: login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{secrets.GIT_SAML_USER}}
          password: ${{secrets.GIT_SAML_TOKEN}}
      - name: Ls
        run: ls
      - name: build and push docker image
        run: |
          pwd
          ls
          docker build -f ./app.Dockerfile . -t imagename-mmm1:v1.1 
          docker tag imagename-mmm1:v1.1 ghcr.io/sailuckyass/learngithubactions/imagename-mmm1:v1.1
          docker push ghcr.io/sailuckyass/learngithubactions/imagename-mmm1:v1.1
        shell: bash
        if: false
      - name: login to conatiner server registry
        uses: Azure/docker-login@v1.0.1
        with:
          username: ${{secrets.GIT_SAML_USER}}
          password: ${{secrets.GIT_SAML_TOKEN}}
          login-server: ghcr.io/sailuckyass/learngithubactions
        if: false
      - name: pull image from ghcr
        run: |
          echo docker pull ghcr.io/sailuckyass/learngithubactions/imagename-mmm:v1.1
          docker pull ghcr.io/sailuckyass/learngithubactions/imagename-mmm:v1.1
        shell: bash
        if: false
        

        
    
  

