name: ci 
on: [push]

jobs:
  Build_And_Test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up jdk
        uses: actions/setup-java@v2
        with: 
          java-version: '17'
          distribution: 'adopt'
      - name: maven build artifacts
        run: |
          mvn clean install -f ./demoGitHub/pom.xml
        shell: bash
      - name: Temp checking files
        run: |
          cd demoGitHub/target
          ls
      - name: code quality
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_SAML_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.branch.name=main -Dsonar.projectKey=SaiLuckyAss_learnGitHubActions -f ./demoGitHub/pom.xml

        
    
  

